package updater

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sync"
	"time"
)

type Service struct { Version string; ExePath string; Dir string; ManifestURL string; Policy UpdatePolicy; Offline bool; Client *http.Client; Spawn func(string,...string) error; Exit func(int); mu sync.Mutex; state UpdateState; logs []string }
func NewService(version string,offline bool)(*Service,error){dir,err:=DataDir();if err!=nil{return nil,err};exe,err:=os.Executable();if err!=nil{return nil,err};manifestURL:=os.Getenv("SELF_UPDATE_MANIFEST_URL");if manifestURL==""{manifestURL=ManifestURL};return &Service{Version:version,ExePath:exe,Dir:dir,ManifestURL:manifestURL,Policy:DefaultPolicy(),Offline:offline,Client:&http.Client{Timeout:10*time.Minute},Spawn:Relaunch,Exit:os.Exit,state:StateChecking},nil}
func(s *Service)State()string{s.mu.Lock();defer s.mu.Unlock();return string(s.state)}
func(s *Service)Logs()[]string{s.mu.Lock();defer s.mu.Unlock();out:=make([]string,len(s.logs));copy(out,s.logs);return out}
func(s *Service)setState(st UpdateState){s.mu.Lock();s.state=st;s.mu.Unlock();s.logf("state=%s",st)}
func(s *Service)logf(format string,args ...any){line:=fmt.Sprintf("[%s] %s",time.Now().UTC().Format("15:04:05"),fmt.Sprintf(format,args...));s.mu.Lock();s.logs=append(s.logs,line);if len(s.logs)>200{s.logs=s.logs[len(s.logs)-200:]};s.mu.Unlock()}
func(s *Service)LogUpdatedFrom(p string){s.logf("khoi dong sau update, updated-from=%s",p)}
func(s *Service)LogRolledBack(){s.logf("khoi dong sau rollback ve %s",s.Version);s.setState(StateRolledBack)}
func(s *Service)PersistedStatus()string{st,err:=LoadState(StatePath(s.Dir));if err!=nil||st.Status==""{return string(StateChecking)};return string(st.Status)}
func(s *Service)Startup()error{path:=StatePath(s.Dir);st,err:=LoadState(path);if err!=nil{s.logf("doc state loi, dung state rong: %v",err);st=PersistentState{}};outcome,evalErr:=EvaluateStartup(&st,s.Version,s.Policy.MaxRollbackAttempts);if evalErr!=nil{s.logf("health-check: %v",evalErr)};switch outcome{case OutcomeHealthy:s.logf("health-check OK, last-known-good=%s",st.LastKnownGood);s.setState(StateUpToDate);case OutcomeRollback:s.logf("pending khong khoi dong duoc, da rollback ve %s",st.LastKnownGood);s.setState(StateRolledBack);default:s.setState(StateUpToDate)};if err:=WriteHealthMarker(HealthDir(s.Dir),s.Version);err!=nil{s.logf("ghi health marker loi: %v",err)};return SaveState(path,st)}
func(s *Service)CheckAndUpdate(ctx context.Context)(*UpdateResult,error){s.setState(StateChecking);if s.Offline{s.logf("offline-test: dung mock provider, khong goi mang");s.setState(StateUpToDate);return MockCheckForUpdate(s.Version,false),nil};var res *UpdateResult;var err error;if s.ManifestURL!=""&&s.ManifestURL!=ManifestURL{res,err=(&Checker{Client:s.Client}).Check(ctx,s.ManifestURL,s.Version,s.Policy)}else{res,err=(&Checker{Client:s.Client}).CheckSources(ctx,UpdateSources,s.Version,s.Policy)};if err!=nil{s.setState(StateFailed);s.logf("kiem tra update loi: %v",err);return nil,err};if !res.HasUpdate{s.logf("da la ban moi nhat (%s)",s.Version);s.setState(StateUpToDate);return res,nil};s.setState(StateUpdateAvailable);s.logf("co ban moi: %s | Release %s | source=%s",res.LatestVersion,res.LatestVersion,res.Source);if !s.Policy.AutoDownload{s.logf("policy autoDownload=false, dung lai");return res,nil};if err:=s.applyUpdate(ctx,res);err!=nil{s.setState(StateFailed);s.logf("cap nhat that bai: %v",err);return res,err};return res,nil}
func(s *Service)applyUpdate(ctx context.Context,res *UpdateResult)error{if res.Manifest==nil{return fmt.Errorf("manifest rong")};s.setState(StateDownloading);dest:=filepath.Join(DownloadDir(s.Dir),res.LatestVersion,filepath.Base(s.ExePath));if err:=DownloadAndVerify(ctx,s.Client,*res.Manifest,dest,VerifyPinnedSignature);err!=nil{return err};s.setState(StateVerifying);s.logf("size + SHA-256 + Minisign OK (key %s)",PinnedKeyID);if !s.Policy.AutoInstall{return nil};s.setState(StateInstalling);statePath:=StatePath(s.Dir);st,err:=LoadState(statePath);if err!=nil{return err};if st.Current==""{st.Current=s.Version};if st.LastKnownGood==""{st.LastKnownGood=s.Version};if err:=StageUpdate(&st,res.LatestVersion);err!=nil{return err};if err:=SaveState(statePath,st);err!=nil{return err};backup,err:=InstallOverSelf(s.ExePath,dest,s.Version);if err!=nil{return err};s.logf("da cai %s, backup=%s",res.LatestVersion,filepath.Base(backup));if !s.Policy.RestartAutomatically{return nil};s.setState(StateRestarting);_=ClearHealthMarker(HealthDir(s.Dir),res.LatestVersion);if err:=s.Spawn(s.ExePath,"--silent-update","--updated-from",s.Version);err!=nil{_=RestoreBackup(s.ExePath,backup);return fmt.Errorf("khong khoi dong duoc ban moi: %w",err)};timeout:=time.Duration(s.Policy.HealthCheckTimeoutSeconds)*time.Second;if WaitForHealthMarker(HealthDir(s.Dir),res.LatestVersion,timeout,300*time.Millisecond){s.logf("ban %s khoi dong OK, tien trinh silent da xac nhan",res.LatestVersion);s.Exit(0);return nil};s.logf("ban moi khong bao healthy trong %s -> rollback",timeout);if err:=RestoreBackup(s.ExePath,backup);err!=nil{return err};if st,err:=LoadState(statePath);err==nil{_=Rollback(&st,s.Policy.MaxRollbackAttempts);_=SaveState(statePath,st)};s.setState(StateRolledBack);if err:=s.Spawn(s.ExePath,"--silent-update","--rolled-back");err!=nil{return err};s.Exit(1);return nil}
